[package]
name = "deps-example"
version = "0.1.0"
authors = ["Jacek Wysocki <jacek.wysocki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
